FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive 
ENV TZ=America/Chicago
RUN apt-get update && apt-get install -y git wget phantomjs && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/FortyNorthSecurity/EyeWitness.git
WORKDIR /EyeWitness/Python/setup
RUN ./setup.sh
RUN mkdir /tmp/EyeWitness
WORKDIR /EyeWitness/Python
COPY nmap.xml /EyeWitness/Python/
ENTRYPOINT ["/usr/bin/python3", "EyeWitness.py", "-x", "nmap.xml"]
