---
- name: Activate Station User
  hosts: all
  gather_facts: no
  tasks:

  - name: Logon to CyberArk Vault using PAS Web Services SDK - Not use_shared_logon_authentication
    cyberark_authentication:
      api_base_url: "{{ web_services_base_url }}"
      username: "{{ ansible_username }}"
      password: "{{ ansible_password }}"
      use_shared_logon_authentication: no

  - name: Disabling a CyberArk User
    cyberark_user:
      username: "{{ user }}"
      disabled: false
      cyberark_session: "{{ cyberark_session }}"
    register: cyberarkaction

  - name: Logoff from CyberArk Vault
    cyberark_authentication:
      state: absent
      cyberark_session: "{{ cyberark_session }}"