---
- name: Ansible Find Example
  hosts: all
  tasks:
   - name : Find files older than 180 days
     become: yes
     find:
       paths: /var/log
       patterns: '*.log'
       age: 180d
       age_stamp: mtime
     register: output

   - name: Delete the files matching
     become: yes
     file:
       path: "{{item.path}}"
       state: absent
     with_items: "{{ output.files }}"
