FROM ubuntu:latest
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Chicago
RUN apt-get update && apt-get install -y git wget phantomjs && rm -rf /var/lib/apt/lists/* \
&& git clone https://github.com/FortyNorthSecurity/EyeWitness.git \
&& mkdir /tmp/EyeWitness
WORKDIR /EyeWitness/Python/setup
RUN ./setup.sh
WORKDIR /EyeWitness/Python
COPY nmap.xml .
ENTRYPOINT ["/usr/bin/python3", "EyeWitness.py", "--no-prompt", "-x", "./nmap.xml"]
