FROM ubuntu:latest
RUN apt-get update && apt-get install -y --no-install-recommends build-essential git ca-certificates \
&& git clone https://github.com/hashcat/hashcat.git . \
&& git submodule update --init \
&& make install \
wget http://downloads.skullsecurity.org/passwords/rockyou.txt.bz2 \
&& bzip2 -d rockyou.txt.bz2
VOLUME /hashcat
#RUN ./hashcat -a 0 -m 1000 ./hashcat/hashes.txt ./hashcat/rockyou.txt -o ./hashcat/cracked.txt
